### ISSUE TITLE
여기서 뭘하는 건가요?

### ISSUE THREAD

**Issue by avocad5** [EntryBlockers/blocks#1]
딱히 질문할곳이 없어서 여기다가 질문합니다

1. 블록들은 누가 합치나요?
2. 합체된 블록들의 이름이나 색깔 등등을 어떻게 누가 정하나요/

**Comment by thoratica** [comment]
아마 DM으로 디스코드 서버 링크가 갔을겁니다.
https://discord.gg/WpKJNez


만약 디스코드 접속이 어려운 상황이시면 다른 가능한 방법을 찾아보겠습니다.
